Adds an arg parser helper function.

diff --git a/scripts/utils b/scripts/utils
--- a/scripts/utils
+++ b/scripts/utils
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
-SCRIPTS_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}))
-APP_DIR=$(dirname $SCRIPTS_DIR)
-logInfo() { [ -z "$1" ] && { printf "[\e[31mERROR\e[0m] No log message provided.\n"; exit 1; } || printf "[\e[33m$(date +'%H:%M:%S')\e[0m] ${1}.\n"; }
-run() { clear && logInfo "Listening.." && make run; }
+SCRIPTS_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}));APP_DIR=$(dirname $SCRIPTS_DIR)
+logInfo() { [ -z "$1" ] && { printf "[\e[31mERROR\e[0m] No log message provided.\n"; exit 1; } || printf "[\e[33m$(date +'%H:%M:%S')\e[0m] ${1}.\n"; }; run() { clear && logInfo "Listening.." && make run; }
+declare -A pArgs=();started=0;workingArg="";workingArgVal=""
+getArgs() {
+  args=("$@"); for arg in "${args[@]}"; do
+    [[ "$arg" == "-"* ]] && { [[ -n "$workingArg" ]] && pArgs["$workingArg"]="${workingArgVal# }"; workingArg="${arg:1}"; workingArgVal=""; } || workingArgVal="${workingArgVal:+$workingArgVal }$arg"
+  done
+  [[ -n "$workingArg" ]] && pArgs["$workingArg"]="${workingArgVal# }"
+}; getArgs "$@"
 
